#!/usr/bin/env python
# encoding: utf-8
"""
@author: kw0ng
@contact: keejiane@gmail.com
@file: settings.py
@time: 2018/3/8 10:34 PM
@desc:
"""

import os

GREP_STRING = "Page generated by:"
# GREP_STRING_BYTES = bytearray(GREP_STRING)
# 盲注文办差异边界值
MAX_RATIO = 0.98
# candidate字段临界值
MIN_DIFF_LEN = 10
# SQL注释标识
GENERIC_SQL_COMMENT = '-- [RANDSTR]'
# 插件工作目录
WORK_PATH = os.getcwd()
# payload的xml文件路径
XML_PAYLOADS_PATH = os.path.join(WORK_PATH, 'xml/payloads')
# boundary的xml文件路径
XML_BOUNDARIES_PATH = os.path.join(WORK_PATH, 'xml/')
# 需要加载的payload文件
PAYLOAD_XML_FILES = ("time_blind.xml", "stacked_queries.xml")
# 需要加载的boundary文件
BOUNDARIES_XML_FILES = XML_BOUNDARIES_PATH + 'boundaries.xml'
# 用于判断报错注入的报错语句正则表达式
ERRORS_XML_FILES = XML_BOUNDARIES_PATH + 'errors.xml'
# 延时注入时间标识
SLEEP_TIME_MARKER = "[SLEEPTIME]"
# 延时注入时间值
SLEEP_TIME_REPLACEMENT = 5
# 生成payloads的等级
PAYLOAD_LEVEL = 2
PAYLOAD_RISK = 3
BOUNDARY_LEVEL = 2
# 生成对应数据库的payload
PAYLOAD_DBMS = []
# Jython jar文件路径
JYTHON_STANDALONE_PATH = '/Users/kwong/SecTools/jython-standalone-2.7.0.jar'
